(ns imgs)

(def logo-base-url "https://raw.githubusercontent.com/codereport/logos/main/")

(def logo-map
  {"Ada"                  "ada.png"
   "Agda"                 "agda.svg"
   "APL"                  "apl.png"
   "Assembly"             "assembly.png"
   "ASP.NET"              "asp.net.jpg"
   "Shell"                "bash.png"
   "BQN"                  "bqn.svg"
   "C"                    "c.png"
   "C++"                  "cpp.png"
   "C#"                   "csharp.png"
   "Chapel"               "chapel.png"
   "Classic Visual Basic" "vb.jpg"
   "Clojure"              "clojure.png"
   "COBOL"                "cobol.png"
   "Common Lisp"          "common_lisp.png"
   "Crystal"              "crystal.svg"
   "CSS"                  "css.png"
   "CUDA"                 "thrust.png"
   "D"                    "d.png"
   "Dart"                 "dart.png"
   "Delphi"               "delphi.png"
   "Elixir"               "elixir.png"
   "Elm"                  "elm.png"
   "Emacs Lisp"           "emacs_lisp.png"
   "Erlang"               "erlang.png"
   "Excel"                "excel.png"
   "F#"                   "fsharp.png"
   "Fortran"              "fortran.png"
   "FoxPro"               "foxpro.png"
   "Futhark"              "futhark.png"
   "Gleam"                "gleam.svg"
   "Go"                   "go.png"
   "Groovy"               "groovy.jpeg"
   "Haskell"              "haskell.svg"
   "HTML"                 "html.svg"
   "J"                    "j.svg"
   "Java"                 "java.png"
   "JavaScript"           "javascript.png"
   "jq"                   "jq.jpg"
   "Julia"                "julia.png"
   "Jupyter Notebook"     "jupyter.png"
   "k"                    "k.png"
   "Kap"                  "kap.png"
   "Kotlin"               "kotlin.svg"
   "LFE"                  "lfe.png"
   "Lisp"                 "lisp.png"
   "Lua"                  "lua.png"
   "Markdown"             "markdown.png"
   "Mathematica"          "mathematica.png"
   "MATLAB"               "matlab.png"
   "NewLisp"              "newlisp.jpg"
   "Nim"                  "nim.png"
   "Objective-C"          "objc.png"
   "OCaml"                "ocaml.jpg"
   "Pascal"               "pascal.png"
   "Perl"                 "perl.png"
   "PicoLisp"             "pico_lisp.png"
   "PLgpSQL"              "plgpsql.png"
   "Pharo"                "pharo.png"
   "PHP"                  "php_circle.png"
   "pandas"               "pandas-logo.png"
   "PowerShell"           "powershell.png"
   "PureScript"           "purescript.png"
   "Python"               "python.png"
   "q"                    "kx.png"
   "R"                    "r.png"
   "Racket"               "racket.png"
   "RAPIDS (C++)"         "rapids.png"
   "RAPIDS (Python)"      "rapids.png"
   "Reason"               "reason.jpg"
   "Ruby"                 "ruby.png"
   "Rust"                 "rust.png"
   "SAS"                  "sas.png"
   "Sass/SCSS"            "sass.png"
   "Scala"                "scala.svg"
   "Scheme"               "scheme.svg"
   "Scratch"              "scratch.png"
   "Solidity"             "solidity.svg"
   "SQL"                  "sql.png"
   "Standard ML"          "sml.png"
   "Swift"                "swift.png"
   "TinyAPL"              "tinyapl.svg"
   "TypeScript"           "ts.png"
   "Uiua"                 "uiua.png"
   "VBA"                  "vba.png"
   "Visual Basic"         "vb.jpg"
   "Visual Basic .NET"    "vb.jpg"
   "Vim Script"           "vim.png"
   "Vue"                  "vue.png"
   "Zig"                  "zig.svg"
   "☾"                    "moon.svg"})

;; Logos with non-square aspect ratios that shouldn't be forced into a square box
(def wide-logos #{"Go" "Scala"})

;; List of languages that have dark mode logo variants
(def darkmode-logos #{"Rust" "Julia" "Kap"})
